# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/google/jsonapi"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
